### PR TITLE
turbolinks support

### PR DESCRIPTION
**Pull request by vieditcom**
Closes cprodhomme/arctic_admin#66

### CODE REVIEW

**Comment by vieditcom** [comment]
Closes #66

**Comment by cprodhomme** [comment]
Hello !

sorry for the late !

How can i test your pull-request ?

How can i use turbolinks on ActiveAdmin ?

**Comment by cprodhomme** [comment]
Hello @vieditcom @frullah  !

sorry for the late !

How can i test your pull-request ?

How can i use turbolinks on ActiveAdmin ?

**Comment by cprodhomme** [comment]
Thanks for your work ! 

I resolve the conflict in the PR : https://github.com/cprodhomme/arctic_admin/pull/109

**Pull request closed without merging**
